version: '3.8'

services:
  php-apache:
    container_name: apache
    restart: always 
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./docker/www:/var/www/html/
    ports:
      - 9000:80

  database:
    container_name: database
    image: mysql:8.0.26
    restart: always
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devops
      MYSQL_PASSWORD: parda433
    ports:
      - "9906:3306"
         
